import type {Metadata} from "next";
import {Manrope} from "next/font/google";
import "./globals.css";
import Providers from "@/app/providers/ Providers";
import {Header} from "@/app/layout/header/Header";


const manrope = Manrope({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={manrope.className}>
        <Providers>
            <Header/>
            {children}
        </Providers>
        </body>
        </html>
    );
}
